import Navbar from "@/components/Navbar";
import { cn } from "@/lib/cn";
import { primaryFont } from "@/lib/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `antialiased min-h-svh  bg-gray-50`,
          primaryFont.className
        )}
      >
        <Navbar />
        <div className="w-[80%] m-auto py-10">{children}</div>
      </body>
    </html>
  );
}
